-- Delveta schema migration 0013 — human-curated Query Corpus (2026-09-25 curation pass).
-- Canonical seed of standard_example / synonym_examples for all 18 user-facing Actions.
-- Draft data ONLY: capabilities draft rows + pre-Registry query drafts (0011).
-- Never writes registry_versions / qir_examples / negatives / examples.
-- Idempotent (DELETE+INSERT) so fresh installs land the same corpus as the curated DB.

UPDATE public.capabilities SET standard_example = '把这个术语加入我的词汇库', synonym_examples = '["Add this term to my glossary.", "将关键词录入生词本", "帮我把这个术语存进生词本", "这个单词收录进我的词汇库", "新词,记到词汇表里去", "我想把这个表达加入我的专业词汇", "把刚才那个单词放进我的生词本", "遇到好词就存一下,录入词汇库", "Save this term to my word list.", "I want to add \"serendipity\" to my personal dictionary.", "File this expression under the finance vocabulary.", "Add this phrase to my collection.", "Can you put this word in my vocab bank?", "Keep this one — add it to my glossary.", "Get this word into my study list.", "把这个单词收进词汇表", "帮我把这个词加入词汇库", "把这个表达保存到我的专业词汇里", "把刚才这个术语记到我的词汇表", "把这个新词添加到我的词汇库", "Add this word to my vocabulary list.", "Save this expression in my glossary.", "Put this term in my vocabulary.", "Add the word I just mentioned to my glossary.", "Keep this term in my vocabulary list."]'::jsonb WHERE capability_id = 'cap-add-term';

UPDATE public.capabilities SET standard_example = '新建一个文件夹', synonym_examples = '["Create a new folder.", "帮我新建一个文件夹", "创建一个新文件夹", "在当前目录建个叫 Notes 的文件夹", "帮我建个目录存这些资料", "新建一个\"数据分析\"目录", "给这个项目建一个专门的文件夹", "建个空文件夹,命名为 Drafts", "这里新建一个子文件夹", "我想建一个归档用的目录", "Create a new folder named Archive.", "Make a directory for my notes.", "I need a folder for this project.", "Set up a subfolder here.", "Can you create a folder called \"Screenshots\"?", "Spin up a new directory to keep the drafts.", "Make me a folder for receipts.", "New folder, name it Experiments.", "新建一个文件夹来放这些文件", "帮我创建一个目录", "在这里建一个新文件夹", "创建一个新的子文件夹", "给这个项目建一个文件夹", "Create a folder here.", "Make a new directory for these files.", "Create a subfolder here.", "Set up a new folder for this project.", "Make a folder to keep these files in."]'::jsonb WHERE capability_id = 'cap-create-folder';

UPDATE public.capabilities SET standard_example = '把这份 PDF 的文字抽出来', synonym_examples = '["Extract the text from this PDF.", "提取全文", "提取附件 PDF 的全文", "帮我把这个 PDF 转成纯文本", "这份 PDF 的文字部分帮我全部拿过来", "PDF 转文本,不要总结,要原文", "把上传的那份 PDF 里所有文字复制出来", "我只要这份 PDF 的原始文本", "这份 PDF 帮我导出文字版", "Extract the full text from this PDF.", "Convert this PDF to plain text.", "Pull the text content of this PDF, not a summary.", "Can you extract raw text from the uploaded PDF?", "I need the verbatim text of this PDF.", "Copy everything in this PDF out as text.", "把这个 PDF 的原始文字提取出来", "只提取 PDF 里的文本内容", "把 PDF 全文导出成纯文本", "从这个 PDF 中提取所有文字", "把上传的 PDF 转成原始文本", "这份 PDF 的原始文字全部提取出来", "Extract all text from this PDF.", "Pull the raw text out of this PDF.", "Convert this PDF into plain text.", "Extract the full text without summarizing it.", "Give me the raw textual content of this PDF."]'::jsonb WHERE capability_id = 'cap-pdf-extract-text';

INSERT INTO public.action_query_drafts (action_key, updated_by) VALUES ('summary', 'seed-0013') ON CONFLICT (action_key) DO UPDATE SET updated_by = 'seed-0013';
DELETE FROM public.action_query_draft_items WHERE action_key = 'summary' AND kind IN ('standard','similar');
INSERT INTO public.action_query_draft_items (action_key, kind, text, position) VALUES
    ('summary', 'standard', '帮我总结一下这份文档', 0),
    ('summary', 'similar', 'Summarize this document for me.', 0),
    ('summary', 'similar', '总结这份材料,列出要点', 1),
    ('summary', 'similar', '这篇文档讲了什么,给我个摘要', 2),
    ('summary', 'similar', '帮我提炼一下这篇文章的核心观点', 3),
    ('summary', 'similar', '把这两个文件的内容做个总结', 4),
    ('summary', 'similar', '太长了,先帮我浓缩一下重点', 5),
    ('summary', 'similar', '给我一份这份白皮书的要点梳理', 6),
    ('summary', 'similar', '快速过一遍这份文件,写个内容概要', 7),
    ('summary', 'similar', '帮我把这份笔记整理成一个简短总结', 8),
    ('summary', 'similar', 'Give me the key points of this paper.', 9),
    ('summary', 'similar', 'What''s this report about? Condense it please.', 10),
    ('summary', 'similar', 'Write a summary of the two files in my workspace.', 11),
    ('summary', 'similar', 'Boil this article down to the essentials.', 12),
    ('summary', 'similar', 'Create a markdown digest of this material with citations.', 13),
    ('summary', 'similar', 'I need a quick overview of this whitepaper.', 14),
    ('summary', 'similar', 'Condense this long document into a short brief.', 15),
    ('summary', 'similar', 'Pull out the main takeaways from these notes.', 16),
    ('summary', 'similar', '概括一下这份材料的主要内容', 17),
    ('summary', 'similar', '帮我提炼这份文档的核心内容', 18),
    ('summary', 'similar', '把这份材料浓缩成几个重点', 19),
    ('summary', 'similar', '给我一个这份文档的简要概述', 20),
    ('summary', 'similar', '提炼一下这篇文章最重要的信息', 21),
    ('summary', 'similar', 'Summarize the main points of this material.', 22),
    ('summary', 'similar', 'Give me a concise overview of this document.', 23),
    ('summary', 'similar', 'Condense this document into its key points.', 24),
    ('summary', 'similar', 'What are the main takeaways from this document?', 25),
    ('summary', 'similar', 'Give me a brief summary of this material.', 26);

INSERT INTO public.action_query_drafts (action_key, updated_by) VALUES ('mindmap', 'seed-0013') ON CONFLICT (action_key) DO UPDATE SET updated_by = 'seed-0013';
DELETE FROM public.action_query_draft_items WHERE action_key = 'mindmap' AND kind IN ('standard','similar');
INSERT INTO public.action_query_draft_items (action_key, kind, text, position) VALUES
    ('mindmap', 'standard', '把这份笔记做成思维导图', 0),
    ('mindmap', 'similar', 'Turn this note into a mind map.', 0),
    ('mindmap', 'similar', '帮我生成一个思维导图', 1),
    ('mindmap', 'similar', '这份材料画个脑图,看看结构', 2),
    ('mindmap', 'similar', '用思维导图梳理这本书的框架', 3),
    ('mindmap', 'similar', '把这几个文件整理成一张 mind map', 4),
    ('mindmap', 'similar', '生成这个课题的思维导图文件', 5),
    ('mindmap', 'similar', '这个大纲做成脑图,mermaid 格式', 6),
    ('mindmap', 'similar', '我想用思维导图复习这些知识点', 7),
    ('mindmap', 'similar', '给这份文档做个分支式的图', 8),
    ('mindmap', 'similar', '整理成思维导图,方便我看清层次', 9),
    ('mindmap', 'similar', 'Make a mindmap of my lecture files.', 10),
    ('mindmap', 'similar', 'Visualize the structure of this document as a tree.', 11),
    ('mindmap', 'similar', 'Build a mermaid mind map from these notes.', 12),
    ('mindmap', 'similar', 'Can you map out this chapter as a diagram with branches?', 13),
    ('mindmap', 'similar', 'I want a mindmap file (.mmd) for this topic.', 14),
    ('mindmap', 'similar', 'Branch out this syllabus into a mind map.', 15),
    ('mindmap', 'similar', 'Draw a mental map of the key concepts here.', 16),
    ('mindmap', 'similar', 'Organize this material into a mindmap for revision.', 17),
    ('mindmap', 'similar', '把这份材料整理成思维导图', 18),
    ('mindmap', 'similar', '用脑图梳理这份内容的结构', 19),
    ('mindmap', 'similar', '把这些知识点组织成一张思维导图', 20),
    ('mindmap', 'similar', '把这篇文章的层级关系画成脑图', 21),
    ('mindmap', 'similar', '帮我把这个主题做成思维导图', 22),
    ('mindmap', 'similar', 'Turn this material into a mind map.', 23),
    ('mindmap', 'similar', 'Map out the structure of these notes.', 24),
    ('mindmap', 'similar', 'Organize these concepts into a mind map.', 25),
    ('mindmap', 'similar', 'Create a mind map showing the hierarchy of this material.', 26),
    ('mindmap', 'similar', 'Build a mind map around this topic.', 27);

INSERT INTO public.action_query_drafts (action_key, updated_by) VALUES ('slides', 'seed-0013') ON CONFLICT (action_key) DO UPDATE SET updated_by = 'seed-0013';
DELETE FROM public.action_query_draft_items WHERE action_key = 'slides' AND kind IN ('standard','similar');
INSERT INTO public.action_query_draft_items (action_key, kind, text, position) VALUES
    ('slides', 'standard', '把这些材料做成一份 PPT', 0),
    ('slides', 'similar', 'Make a slide deck from these files.', 0),
    ('slides', 'similar', '帮我生成一份演示文稿', 1),
    ('slides', 'similar', '这份报告转成幻灯片', 2),
    ('slides', 'similar', '用这几个文件做一套 slides,10 页左右', 3),
    ('slides', 'similar', '把这个笔记做成 PPT 给我', 4),
    ('slides', 'similar', '下周要汇报,帮我做份演示稿', 5),
    ('slides', 'similar', '生成一个 16:9 的 PPT,内容是这份文档', 6),
    ('slides', 'similar', '把这篇论文做成讲课用的幻灯片', 7),
    ('slides', 'similar', '做一套介绍这个项目的 slides', 8),
    ('slides', 'similar', '帮我做个 PPTX,主题参考这份材料', 9),
    ('slides', 'similar', 'Turn this report into slides.', 10),
    ('slides', 'similar', 'Create a presentation about this topic, around 10 slides.', 11),
    ('slides', 'similar', 'I need a PPTX for next week''s meeting.', 12),
    ('slides', 'similar', 'Build a deck out of my research notes.', 13),
    ('slides', 'similar', 'Can you convert this paper into lecture slides?', 14),
    ('slides', 'similar', 'Put together some presentation slides from this document.', 15),
    ('slides', 'similar', 'Generate a 16:9 deck for this project overview.', 16),
    ('slides', 'similar', 'Reformat this material as a talk deck.', 17),
    ('slides', 'similar', '把这份材料做成演示文稿', 18),
    ('slides', 'similar', '根据这篇文档生成一套幻灯片', 19),
    ('slides', 'similar', '把这些内容整理成汇报 PPT', 20),
    ('slides', 'similar', '把这份报告制作成一套 slides', 21),
    ('slides', 'similar', '帮我把这个主题做成 PPT', 22),
    ('slides', 'similar', 'Turn this material into a presentation.', 23),
    ('slides', 'similar', 'Create slides from this document.', 24),
    ('slides', 'similar', 'Build a presentation from these materials.', 25),
    ('slides', 'similar', 'Make a presentation deck for this topic.', 26),
    ('slides', 'similar', 'Convert these notes into a slide deck.', 27);

INSERT INTO public.action_query_drafts (action_key, updated_by) VALUES ('rag_search', 'seed-0013') ON CONFLICT (action_key) DO UPDATE SET updated_by = 'seed-0013';
DELETE FROM public.action_query_draft_items WHERE action_key = 'rag_search' AND kind IN ('standard','similar');
INSERT INTO public.action_query_draft_items (action_key, kind, text, position) VALUES
    ('rag_search', 'standard', '在我导入的资料里查一下这个问题', 0),
    ('rag_search', 'similar', 'Search my imported materials for this topic.', 0),
    ('rag_search', 'similar', '搜一下我的资料库里关于神经网络的笔记', 1),
    ('rag_search', 'similar', '我之前上传的文档里有没有提到这个', 2),
    ('rag_search', 'similar', '查我的资料:这个项目的预算是多少', 3),
    ('rag_search', 'similar', '帮我检索知识库里的相关内容', 4),
    ('rag_search', 'similar', '我导入的论文里,谁写过这个观点', 5),
    ('rag_search', 'similar', '在我的学习材料中找一下相关内容', 6),
    ('rag_search', 'similar', '知识库检索:通货膨胀相关的段落', 7),
    ('rag_search', 'similar', '翻翻我存的文件,看看有没有讲这个的', 8),
    ('rag_search', 'similar', '帮我在自己上传过的文件里搜一下关键词', 9),
    ('rag_search', 'similar', 'Find passages in my own documents about this.', 10),
    ('rag_search', 'similar', 'What did my saved notes say about this?', 11),
    ('rag_search', 'similar', 'Query my knowledge base for related content.', 12),
    ('rag_search', 'similar', 'Look this up in the files I uploaded before.', 13),
    ('rag_search', 'similar', 'Retrieve anything in my library about this claim.', 14),
    ('rag_search', 'similar', 'Can you search across my personal corpus?', 15),
    ('rag_search', 'similar', 'Dig through my archives for this reference.', 16),
    ('rag_search', 'similar', 'Check my study materials for the answer.', 17),
    ('rag_search', 'similar', '在我的知识库里找一下这个问题', 18),
    ('rag_search', 'similar', '从我已有的资料中检索相关内容', 19),
    ('rag_search', 'similar', '查一下我之前导入的文档有没有提到这个', 20),
    ('rag_search', 'similar', '在我的资料库里找和这个问题相关的信息', 21),
    ('rag_search', 'similar', '从我自己的资料中搜索这个概念', 22),
    ('rag_search', 'similar', 'Search my knowledge base for this.', 23),
    ('rag_search', 'similar', 'Find this information in my imported documents.', 24),
    ('rag_search', 'similar', 'Search my own materials for relevant passages.', 25),
    ('rag_search', 'similar', 'Look through my uploaded documents for this.', 26),
    ('rag_search', 'similar', 'Find references to this in my personal knowledge base.', 27);

INSERT INTO public.action_query_drafts (action_key, updated_by) VALUES ('web_search', 'seed-0013') ON CONFLICT (action_key) DO UPDATE SET updated_by = 'seed-0013';
DELETE FROM public.action_query_draft_items WHERE action_key = 'web_search' AND kind IN ('standard','similar');
INSERT INTO public.action_query_draft_items (action_key, kind, text, position) VALUES
    ('web_search', 'standard', '上网搜一下最新的这个消息', 0),
    ('web_search', 'similar', 'Search the web for the latest news on this.', 0),
    ('web_search', 'similar', '帮我查一下网上怎么说的', 1),
    ('web_search', 'similar', '搜一下这个产品的官网价格', 2),
    ('web_search', 'similar', '看看互联网上最新的资料', 3),
    ('web_search', 'similar', '这个问题网上有答案吗,搜一下', 4),
    ('web_search', 'similar', '查一下今天的相关新闻', 5),
    ('web_search', 'similar', '检索一下这个概念在网上的定义', 6),
    ('web_search', 'similar', '我想看看外面网站上的说法,帮我搜', 7),
    ('web_search', 'similar', '到网上找一下这篇报道', 8),
    ('web_search', 'similar', '搜索一下这个事件最近的发展', 9),
    ('web_search', 'similar', 'Look this up online for me.', 10),
    ('web_search', 'similar', 'What does the internet say about this?', 11),
    ('web_search', 'similar', 'Check current information on this topic online.', 12),
    ('web_search', 'similar', 'Can you find this on the public web?', 13),
    ('web_search', 'similar', 'Run a web search for this product''s pricing.', 14),
    ('web_search', 'similar', 'Find a recent article about this event.', 15),
    ('web_search', 'similar', 'Pull up up-to-date info from the web.', 16),
    ('web_search', 'similar', 'Search online for what''s new on this.', 17),
    ('web_search', 'similar', '去网上查一下这个问题', 18),
    ('web_search', 'similar', '帮我在互联网上搜索这个信息', 19),
    ('web_search', 'similar', '看看公开网页上有没有相关资料', 20),
    ('web_search', 'similar', '搜索一下网上关于这个主题的信息', 21),
    ('web_search', 'similar', '帮我查一下最新的公开信息', 22),
    ('web_search', 'similar', 'Search the public web for this.', 23),
    ('web_search', 'similar', 'Look this up on the internet.', 24),
    ('web_search', 'similar', 'Find information about this online.', 25),
    ('web_search', 'similar', 'Search online for current information on this.', 26),
    ('web_search', 'similar', 'Check the web for information about this topic.', 27);

INSERT INTO public.action_query_drafts (action_key, updated_by) VALUES ('read_document', 'seed-0013') ON CONFLICT (action_key) DO UPDATE SET updated_by = 'seed-0013';
DELETE FROM public.action_query_draft_items WHERE action_key = 'read_document' AND kind IN ('standard','similar');
INSERT INTO public.action_query_draft_items (action_key, kind, text, position) VALUES
    ('read_document', 'standard', '帮我阅读这份文档', 0),
    ('read_document', 'similar', 'Read through this document for me.', 0),
    ('read_document', 'similar', '打开这个附件,给我看看文档内容', 1),
    ('read_document', 'similar', '这份 PDF 第三页写了什么', 2),
    ('read_document', 'similar', '帮我通读一下这篇文档', 3),
    ('read_document', 'similar', '看一下这个文档的章节结构', 4),
    ('read_document', 'similar', '第 5 到第 8 页讲了什么', 5),
    ('read_document', 'similar', '这个 docx 里写了啥,读一遍给我', 6),
    ('read_document', 'similar', '这个附件能打开吗,读一下正文', 7),
    ('read_document', 'similar', '把这份文档从头到尾读给我', 8),
    ('read_document', 'similar', 'Show me what''s in this attached document.', 9),
    ('read_document', 'similar', 'What does page 3 of this PDF say?', 10),
    ('read_document', 'similar', 'Walk me through the content of this attachment.', 11),
    ('read_document', 'similar', 'Open the document and print out its structure.', 12),
    ('read_document', 'similar', 'Can you read out pages 5 through 8?', 13),
    ('read_document', 'similar', 'Check the body text of this uploaded doc.', 14),
    ('read_document', 'similar', 'I want to go through this document page by page.', 15),
    ('read_document', 'similar', '帮我读一下这份 PDF', 16),
    ('read_document', 'similar', '看看这份文档主要讲了什么', 17),
    ('read_document', 'similar', '阅读这份文档的内容', 18),
    ('read_document', 'similar', '帮我看看这篇文档', 19),
    ('read_document', 'similar', '读一下这篇文档的章节内容', 20),
    ('read_document', 'similar', '看看这份文档的结构', 21),
    ('read_document', 'similar', '帮我逐页阅读这份 PDF', 22),
    ('read_document', 'similar', '逐页阅读这份 PDF，告诉我每页主要讲了什么', 23),
    ('read_document', 'similar', 'Read through this PDF for me.', 24),
    ('read_document', 'similar', 'Read the contents of this document.', 25),
    ('read_document', 'similar', 'Go through this document with me.', 26),
    ('read_document', 'similar', 'Read this document section by section.', 27),
    ('read_document', 'similar', 'Take me through the contents of this document.', 28),
    ('read_document', 'similar', 'Read through this uploaded document.', 29),
    ('read_document', 'similar', 'Read this PDF page by page.', 30),
    ('read_document', 'similar', 'Read this PDF page by page and tell me what each page is about.', 31);

INSERT INTO public.action_query_drafts (action_key, updated_by) VALUES ('read_file', 'seed-0013') ON CONFLICT (action_key) DO UPDATE SET updated_by = 'seed-0013';
DELETE FROM public.action_query_draft_items WHERE action_key = 'read_file' AND kind IN ('standard','similar');
INSERT INTO public.action_query_draft_items (action_key, kind, text, position) VALUES
    ('read_file', 'standard', '读取这个工作区里的文件', 0),
    ('read_file', 'similar', 'Read this file from the workspace.', 0),
    ('read_file', 'similar', '打开 notes.md 给我看看', 1),
    ('read_file', 'similar', '看一下工作区里 config.txt 写了什么', 2),
    ('read_file', 'similar', '这个 json 文件内容帮我读出来', 3),
    ('read_file', 'similar', '把 readme 显示一下', 4),
    ('read_file', 'similar', '看看 main.py 里的源码', 5),
    ('read_file', 'similar', '帮我读一下 data.csv 的前几行', 6),
    ('read_file', 'similar', '输出这个文本文件的内容', 7),
    ('read_file', 'similar', '我这个脚本文件里写了啥', 8),
    ('read_file', 'similar', '把 todo.md 打开检查一下', 9),
    ('read_file', 'similar', 'Open notes.md and show me the content.', 10),
    ('read_file', 'similar', 'What''s inside config.txt?', 11),
    ('read_file', 'similar', 'Print the contents of readme.', 12),
    ('read_file', 'similar', 'Show me main.py.', 13),
    ('read_file', 'similar', 'Can you display this text file?', 14),
    ('read_file', 'similar', 'Read data.csv for me.', 15),
    ('read_file', 'similar', 'Output the body of that script.', 16),
    ('read_file', 'similar', 'Take a look at todo.md and paste what''s in it.', 17),
    ('read_file', 'similar', '打开 workspace 里的这个文件看看', 18),
    ('read_file', 'similar', '读取 src/main.py', 19),
    ('read_file', 'similar', '看看这个配置文件里面写了什么', 20),
    ('read_file', 'similar', '把这个文件的内容显示出来', 21),
    ('read_file', 'similar', '打开这个 markdown 文件给我看看', 22),
    ('read_file', 'similar', '读取这个 JSON 文件', 23),
    ('read_file', 'similar', '看看这个脚本文件的内容', 24),
    ('read_file', 'similar', 'Open this workspace file and show me its contents.', 25),
    ('read_file', 'similar', 'Read this file from my workspace.', 26),
    ('read_file', 'similar', 'Show me what''s inside this file.', 27),
    ('read_file', 'similar', 'Open this source file and read it.', 28),
    ('read_file', 'similar', 'Read the contents of this config file.', 29),
    ('read_file', 'similar', 'Show me the contents of this markdown file.', 30),
    ('read_file', 'similar', 'Read this JSON file for me.', 31);

INSERT INTO public.action_query_drafts (action_key, updated_by) VALUES ('edit_file', 'seed-0013') ON CONFLICT (action_key) DO UPDATE SET updated_by = 'seed-0013';
DELETE FROM public.action_query_draft_items WHERE action_key = 'edit_file' AND kind IN ('standard','similar');
INSERT INTO public.action_query_draft_items (action_key, kind, text, position) VALUES
    ('edit_file', 'standard', '把这个文件里的标题行改一下', 0),
    ('edit_file', 'similar', 'Edit this file and update the title line.', 0),
    ('edit_file', 'similar', '帮我把 readme 里的错别字改一下', 1),
    ('edit_file', 'similar', '把 note.txt 中第一行删掉', 2),
    ('edit_file', 'similar', '在 config 文件里把端口号改成 8300', 3),
    ('edit_file', 'similar', '修改这个文件里的这段文字', 4),
    ('edit_file', 'similar', '把脚本里的旧地址替换成新地址', 5),
    ('edit_file', 'similar', 'todo.md 里那条任务帮我改成已完成', 6),
    ('edit_file', 'similar', '编辑一下这个 txt,追加一行内容', 7),
    ('edit_file', 'similar', '这个 markdown 的二级标题换掉', 8),
    ('edit_file', 'similar', '把文件里的公司名统一替换成新的', 9),
    ('edit_file', 'similar', 'Update the title line in this file.', 10),
    ('edit_file', 'similar', 'Fix the typo in notes.txt.', 11),
    ('edit_file', 'similar', 'Replace the old URL with the new one in this script.', 12),
    ('edit_file', 'similar', 'Change the port number in config.', 13),
    ('edit_file', 'similar', 'Can you edit readme.md and delete the first line?', 14),
    ('edit_file', 'similar', 'Mark that task as done in todo.md.', 15),
    ('edit_file', 'similar', 'Swap this paragraph for a shorter version in the file.', 16),
    ('edit_file', 'similar', 'Make a small text change in my markdown file.', 17),
    ('edit_file', 'similar', '修改这个文件里的内容', 18),
    ('edit_file', 'similar', '把这个文件中的一段文字替换掉', 19),
    ('edit_file', 'similar', '帮我编辑这个文件', 20),
    ('edit_file', 'similar', '把这个配置文件里的值改掉', 21),
    ('edit_file', 'similar', '在这个文件末尾追加一行', 22),
    ('edit_file', 'similar', '删除文件中的这一行', 23),
    ('edit_file', 'similar', 'Edit this file and change the content.', 24),
    ('edit_file', 'similar', 'Replace this text in the file.', 25),
    ('edit_file', 'similar', 'Modify this workspace file.', 26),
    ('edit_file', 'similar', 'Change this value in the config file.', 27),
    ('edit_file', 'similar', 'Append a line to this file.', 28),
    ('edit_file', 'similar', 'Delete this line from the file.', 29),
    ('edit_file', 'similar', 'Update the date in the header of this workspace file.', 30);

INSERT INTO public.action_query_drafts (action_key, updated_by) VALUES ('bash', 'seed-0013') ON CONFLICT (action_key) DO UPDATE SET updated_by = 'seed-0013';
DELETE FROM public.action_query_draft_items WHERE action_key = 'bash' AND kind IN ('standard','similar');
INSERT INTO public.action_query_draft_items (action_key, kind, text, position) VALUES
    ('bash', 'standard', '在工作区运行这个命令', 0),
    ('bash', 'similar', 'Run this command in the workspace.', 0),
    ('bash', 'similar', '执行一下 ls,看看有哪些文件', 1),
    ('bash', 'similar', '帮我跑个命令统计文件行数', 2),
    ('bash', 'similar', '运行 python analyze.py 看看输出', 3),
    ('bash', 'similar', '在终端里执行这条指令', 4),
    ('bash', 'similar', '用命令行把这个目录列一下', 5),
    ('bash', 'similar', '帮我跑一下这段 shell 脚本', 6),
    ('bash', 'similar', '执行 npm install 装一下依赖', 7),
    ('bash', 'similar', '在工作区里跑 wc -l notes.md', 8),
    ('bash', 'similar', '帮我执行 pwd,看看当前目录', 9),
    ('bash', 'similar', 'Execute ls and show me the output.', 10),
    ('bash', 'similar', 'Can you run python analyze.py for me?', 11),
    ('bash', 'similar', 'Execute this shell script.', 12),
    ('bash', 'similar', 'Run wc -l on notes.md.', 13),
    ('bash', 'similar', 'Type this into the terminal and tell me what prints.', 14),
    ('bash', 'similar', 'Fire off npm install in the workspace.', 15),
    ('bash', 'similar', 'Do a pwd to check the current directory.', 16),
    ('bash', 'similar', 'Run the build command and paste the result.', 17),
    ('bash', 'similar', '在终端执行这条命令', 18),
    ('bash', 'similar', '帮我运行一下这个 shell 命令', 19),
    ('bash', 'similar', '在 workspace 里执行这个脚本', 20),
    ('bash', 'similar', '运行这个命令并把输出告诉我', 21),
    ('bash', 'similar', '帮我在命令行里执行一下', 22),
    ('bash', 'similar', '执行一下这个构建命令', 23),
    ('bash', 'similar', 'Run this command in the terminal.', 24),
    ('bash', 'similar', 'Execute this shell command.', 25),
    ('bash', 'similar', 'Run this script in the workspace.', 26),
    ('bash', 'similar', 'Execute the command and show me the output.', 27),
    ('bash', 'similar', 'Run this from the command line.', 28),
    ('bash', 'similar', 'Execute this build command.', 29);

INSERT INTO public.action_query_drafts (action_key, updated_by) VALUES ('translate', 'seed-0013') ON CONFLICT (action_key) DO UPDATE SET updated_by = 'seed-0013';
DELETE FROM public.action_query_draft_items WHERE action_key = 'translate' AND kind IN ('standard','similar');
INSERT INTO public.action_query_draft_items (action_key, kind, text, position) VALUES
    ('translate', 'standard', '把这段话翻译成英文', 0),
    ('translate', 'similar', 'Translate this sentence into English.', 0),
    ('translate', 'similar', '这段中文帮我翻成英文', 1),
    ('translate', 'similar', '把下面这段翻成日语', 2),
    ('translate', 'similar', '帮我把这句英文翻译成中文', 3),
    ('translate', 'similar', '这个单词用法语怎么说', 4),
    ('translate', 'similar', '把这段文字翻译成西班牙语', 5),
    ('translate', 'similar', '这份邮件内容翻成中文给我', 6),
    ('translate', 'similar', '这句话用地道的英文该怎么表达', 7),
    ('translate', 'similar', '将以下段落译为英文', 8),
    ('translate', 'similar', '这个牌子上的韩文帮我翻译一下', 9),
    ('translate', 'similar', 'How do you say this in French?', 10),
    ('translate', 'similar', 'Can you translate this paragraph into Chinese?', 11),
    ('translate', 'similar', 'Render this text in Spanish.', 12),
    ('translate', 'similar', 'What''s the English for this phrase?', 13),
    ('translate', 'similar', 'Please translate the following into German.', 14),
    ('translate', 'similar', 'Turn this Korean text into English.', 15),
    ('translate', 'similar', 'Translate this blurb into natural English.', 16),
    ('translate', 'similar', 'I need this passage in Japanese — can you do it?', 17),
    ('translate', 'similar', '把下面这段文字翻译成中文', 18),
    ('translate', 'similar', '帮我把这句话译成英文', 19),
    ('translate', 'similar', '把这段内容翻译成日语', 20),
    ('translate', 'similar', '这句话用英文怎么说', 21),
    ('translate', 'similar', '帮我把这段话翻译成法语', 22),
    ('translate', 'similar', '把下面的文本翻译一下', 23),
    ('translate', 'similar', 'Translate this text into Chinese.', 24),
    ('translate', 'similar', 'How would you say this in English?', 25),
    ('translate', 'similar', 'Translate this passage into Japanese.', 26),
    ('translate', 'similar', 'Translate the following text into French.', 27),
    ('translate', 'similar', 'Can you translate this paragraph for me?', 28);

INSERT INTO public.action_query_drafts (action_key, updated_by) VALUES ('vision', 'seed-0013') ON CONFLICT (action_key) DO UPDATE SET updated_by = 'seed-0013';
DELETE FROM public.action_query_draft_items WHERE action_key = 'vision' AND kind IN ('standard','similar');
INSERT INTO public.action_query_draft_items (action_key, kind, text, position) VALUES
    ('vision', 'standard', '看一下这张图片里是什么', 0),
    ('vision', 'similar', 'Look at this image and tell me what you see.', 0),
    ('vision', 'similar', '这张截图里报了什么错', 1),
    ('vision', 'similar', '帮我分析这个图表的数据', 2),
    ('vision', 'similar', '这张图的内容描述一下', 3),
    ('vision', 'similar', '这个流程图讲的什么逻辑', 4),
    ('vision', 'similar', '图里的文字帮我识别出来', 5),
    ('vision', 'similar', '看看这张照片拍的是什么', 6),
    ('vision', 'similar', '这个 UI 截图有什么问题,帮我看看', 7),
    ('vision', 'similar', '解析一下这张架构图', 8),
    ('vision', 'similar', '这张图片里的表格数字帮我读出来', 9),
    ('vision', 'similar', 'What''s the error in this screenshot?', 10),
    ('vision', 'similar', 'Analyze this chart for me.', 11),
    ('vision', 'similar', 'Can you read the text in this picture?', 12),
    ('vision', 'similar', 'Describe what''s happening in this photo.', 13),
    ('vision', 'similar', 'Break down this architecture diagram.', 14),
    ('vision', 'similar', 'Does this UI screenshot look off anywhere?', 15),
    ('vision', 'similar', 'What data does this graph show?', 16),
    ('vision', 'similar', 'Explain this flowchart step by step.', 17),
    ('vision', 'similar', '分析一下这张图片', 18),
    ('vision', 'similar', '看看这张截图有什么问题', 19),
    ('vision', 'similar', '识别一下图片里的内容', 20),
    ('vision', 'similar', '帮我看看这个截图', 21),
    ('vision', 'similar', '解释一下这张图表', 22),
    ('vision', 'similar', '看看这张架构图表达了什么', 23),
    ('vision', 'similar', '读取一下图片里的文字', 24),
    ('vision', 'similar', '分析这张图片中的信息', 25),
    ('vision', 'similar', 'Analyze this image for me.', 26),
    ('vision', 'similar', 'What does this screenshot show?', 27),
    ('vision', 'similar', 'Can you inspect this image?', 28),
    ('vision', 'similar', 'Explain what this chart shows.', 29),
    ('vision', 'similar', 'What does this diagram mean?', 30),
    ('vision', 'similar', 'Read the text in this image.', 31),
    ('vision', 'similar', 'Analyze the information in this picture.', 32),
    ('vision', 'similar', 'Take a look at this screenshot.', 33);

INSERT INTO public.action_query_drafts (action_key, updated_by) VALUES ('pdf_table_to_text', 'seed-0013') ON CONFLICT (action_key) DO UPDATE SET updated_by = 'seed-0013';
DELETE FROM public.action_query_draft_items WHERE action_key = 'pdf_table_to_text' AND kind IN ('standard','similar');
INSERT INTO public.action_query_draft_items (action_key, kind, text, position) VALUES
    ('pdf_table_to_text', 'standard', '把这份 PDF 里的表格转成文字', 0),
    ('pdf_table_to_text', 'similar', 'Convert the tables in this PDF to text.', 0),
    ('pdf_table_to_text', 'similar', 'PDF 里的表格提取出来,转成文本', 1),
    ('pdf_table_to_text', 'similar', '这份文件的表格帮我导出成文字版', 2),
    ('pdf_table_to_text', 'similar', '把附件里第 2 页那个表转成纯文本', 3),
    ('pdf_table_to_text', 'similar', '这个 PDF 的表格能变成可编辑的文字吗', 4),
    ('pdf_table_to_text', 'similar', '提取这份 PDF 所有表格的内容', 5),
    ('pdf_table_to_text', 'similar', '表格部分帮我转文字,正文不用', 6),
    ('pdf_table_to_text', 'similar', '这份年报里的表格数据导出来', 7),
    ('pdf_table_to_text', 'similar', '把 PDF 中的三线表还原成文本', 8),
    ('pdf_table_to_text', 'similar', '这个文档里表格中的数字帮我弄成文本', 9),
    ('pdf_table_to_text', 'similar', 'Extract the tabular data from this file.', 10),
    ('pdf_table_to_text', 'similar', 'Can you turn the PDF''s tables into plain text?', 11),
    ('pdf_table_to_text', 'similar', 'Export the tables on page 2 as text.', 12),
    ('pdf_table_to_text', 'similar', 'Pull the numbers out of the tables in this PDF.', 13),
    ('pdf_table_to_text', 'similar', 'Make the tables in this attachment editable text.', 14),
    ('pdf_table_to_text', 'similar', 'Convert only the tables, not the body text.', 15),
    ('pdf_table_to_text', 'similar', 'I need the financial tables from this report as text.', 16),
    ('pdf_table_to_text', 'similar', 'Get the table contents out of this PDF.', 17),
    ('pdf_table_to_text', 'similar', '提取这份 PDF 里的表格', 18),
    ('pdf_table_to_text', 'similar', '把 PDF 中的表格转换成文本', 19),
    ('pdf_table_to_text', 'similar', '只提取 PDF 里的表格内容', 20),
    ('pdf_table_to_text', 'similar', '把这份 PDF 的表格数据导出来', 21),
    ('pdf_table_to_text', 'similar', '提取 PDF 中所有表格的文字内容', 22),
    ('pdf_table_to_text', 'similar', '把 PDF 表格转成可编辑文本', 23),
    ('pdf_table_to_text', 'similar', 'Extract the tables from this PDF.', 24),
    ('pdf_table_to_text', 'similar', 'Convert the PDF tables into text.', 25),
    ('pdf_table_to_text', 'similar', 'Extract only the tables from this PDF.', 26),
    ('pdf_table_to_text', 'similar', 'Export the table data from this PDF.', 27),
    ('pdf_table_to_text', 'similar', 'Pull the tabular content out of this PDF.', 28),
    ('pdf_table_to_text', 'similar', 'Turn the tables in this PDF into editable text.', 29);

INSERT INTO public.action_query_drafts (action_key, updated_by) VALUES ('research', 'seed-0013') ON CONFLICT (action_key) DO UPDATE SET updated_by = 'seed-0013';
DELETE FROM public.action_query_draft_items WHERE action_key = 'research' AND kind IN ('standard','similar');
INSERT INTO public.action_query_draft_items (action_key, kind, text, position) VALUES
    ('research', 'standard', '针对这个课题做一次深度研究', 0),
    ('research', 'similar', 'Run a deep research project on this topic.', 0),
    ('research', 'similar', '帮我立项研究一下这个方向', 1),
    ('research', 'similar', '就这个话题做一次系统的调研', 2),
    ('research', 'similar', '开始一个新的研究项目:固态电池', 3),
    ('research', 'similar', '这个课题帮我做多步骤的深入研究', 4),
    ('research', 'similar', '围绕这个问题展开调研,要带证据链', 5),
    ('research', 'similar', '推进一下我的研究项目,下一步该做什么', 6),
    ('research', 'similar', '对这个领域做一次全面调研并出报告', 7),
    ('research', 'similar', '建一个研究计划,主题就是这个', 8),
    ('research', 'similar', '帮我把这个研究任务继续跑完', 9),
    ('research', 'similar', 'Start a research project about this.', 10),
    ('research', 'similar', 'Can you do an in-depth investigation with evidence for me?', 11),
    ('research', 'similar', 'I want a systematic dig into this question.', 12),
    ('research', 'similar', 'Kick off a research task on this theme.', 13),
    ('research', 'similar', 'Advance my research project to the next stage.', 14),
    ('research', 'similar', 'Put together a full research report on this area.', 15),
    ('research', 'similar', 'Set up a study plan for this subject.', 16),
    ('research', 'similar', 'Continue my ongoing research run.', 17),
    ('research', 'similar', '对这个问题做一次深入研究', 18),
    ('research', 'similar', '围绕这个主题展开系统研究', 19),
    ('research', 'similar', '帮我对这个课题进行深度调研', 20),
    ('research', 'similar', '针对这个问题做一次完整的研究', 21),
    ('research', 'similar', '建立一个研究项目来研究这个问题', 22),
    ('research', 'similar', '对这个主题进行多步骤研究', 23),
    ('research', 'similar', '帮我调查这个问题并整理证据', 24),
    ('research', 'similar', 'Do a deep investigation into this topic.', 25),
    ('research', 'similar', 'Conduct a systematic research project on this question.', 26),
    ('research', 'similar', 'Research this topic in depth.', 27),
    ('research', 'similar', 'Start a structured research project on this subject.', 28),
    ('research', 'similar', 'Investigate this question and gather evidence.', 29),
    ('research', 'similar', 'Carry out a multi-step research task on this topic.', 30),
    ('research', 'similar', 'Do a thorough investigation of this issue.', 31);

INSERT INTO public.action_query_drafts (action_key, updated_by) VALUES ('artifact', 'seed-0013') ON CONFLICT (action_key) DO UPDATE SET updated_by = 'seed-0013';
DELETE FROM public.action_query_draft_items WHERE action_key = 'artifact' AND kind IN ('standard','similar');
INSERT INTO public.action_query_draft_items (action_key, kind, text, position) VALUES
    ('artifact', 'standard', '把研究成果编译发布成 PDF', 0),
    ('artifact', 'similar', 'Compile the research artifact into a published PDF.', 0),
    ('artifact', 'similar', '这个研究的成果帮我编译成 PDF', 1),
    ('artifact', 'similar', '发布这个 artifact,生成正式版文件', 2),
    ('artifact', 'similar', '把研究项目里的报告导出成 PDF', 3),
    ('artifact', 'similar', '这个版本编译一下,出版本 PDF', 4),
    ('artifact', 'similar', '帮我重新编译这个 artifact', 5),
    ('artifact', 'similar', '研究的最终产物整理成 PDF 发布', 6),
    ('artifact', 'similar', '把这个 artifact 的最新版发布出来', 7),
    ('artifact', 'similar', '帮我出一个编译好的版本', 8),
    ('artifact', 'similar', '课题报告的 PDF 编译一下', 9),
    ('artifact', 'similar', 'Publish the latest version of this artifact.', 10),
    ('artifact', 'similar', 'Can you build the PDF for my research report?', 11),
    ('artifact', 'similar', 'Re-compile this artifact after the edits.', 12),
    ('artifact', 'similar', 'Export the artifact as a final PDF.', 13),
    ('artifact', 'similar', 'Generate the published version of the report.', 14),
    ('artifact', 'similar', 'Push this artifact through the compiler.', 15),
    ('artifact', 'similar', 'I want the artifact rendered to PDF.', 16),
    ('artifact', 'similar', 'Compile the next version of my research deliverable.', 17),
    ('artifact', 'similar', '把这个研究成果编译成 PDF', 18),
    ('artifact', 'similar', '编译这份研究报告的最终版本', 19),
    ('artifact', 'similar', '把研究产物渲染成 PDF', 20),
    ('artifact', 'similar', '重新编译这个 artifact', 21),
    ('artifact', 'similar', '生成研究报告的正式 PDF', 22),
    ('artifact', 'similar', '把最终研究成果发布成 PDF', 23),
    ('artifact', 'similar', 'Compile this research artifact into a PDF.', 24),
    ('artifact', 'similar', 'Build the final PDF for this research report.', 25),
    ('artifact', 'similar', 'Render this research artifact as a PDF.', 26),
    ('artifact', 'similar', 'Recompile this artifact.', 27),
    ('artifact', 'similar', 'Generate the final PDF for the research report.', 28),
    ('artifact', 'similar', 'Publish the compiled research deliverable as a PDF.', 29);

INSERT INTO public.action_query_drafts (action_key, updated_by) VALUES ('social_search', 'seed-0013') ON CONFLICT (action_key) DO UPDATE SET updated_by = 'seed-0013';
DELETE FROM public.action_query_draft_items WHERE action_key = 'social_search' AND kind IN ('standard','similar');
INSERT INTO public.action_query_draft_items (action_key, kind, text, position) VALUES
    ('social_search', 'standard', '在 Reddit 上搜一下大家的讨论', 0),
    ('social_search', 'similar', 'Search Reddit for what people are saying about this.', 0),
    ('social_search', 'similar', '看看社交平台上这个话题的风评', 1),
    ('social_search', 'similar', '搜一下 reddit 上有没有人遇到过同样问题', 2),
    ('social_search', 'similar', '大家的社区讨论里怎么说这个产品', 3),
    ('social_search', 'similar', '帮我找找相关的论坛帖子', 4),
    ('social_search', 'similar', 'Reddit 上有人推荐过这个吗', 5),
    ('social_search', 'similar', '社群里关于这个的热门帖子搜一下', 6),
    ('social_search', 'similar', '社交平台搜一下这个关键词', 7),
    ('social_search', 'similar', '看看国外论坛的用户反馈', 8),
    ('social_search', 'similar', '社区里有没有人讨论过这个报错', 9),
    ('social_search', 'similar', 'Any threads on social platforms about this issue?', 10),
    ('social_search', 'similar', 'Check community discussions on this product.', 11),
    ('social_search', 'similar', 'Find reddit posts where users reviewed this.', 12),
    ('social_search', 'similar', 'Search social media for chatter about this topic.', 13),
    ('social_search', 'similar', 'What are people on forums recommending?', 14),
    ('social_search', 'similar', 'Can you look up this error in reddit discussions?', 15),
    ('social_search', 'similar', 'Scour subreddits for firsthand experiences.', 16),
    ('social_search', 'similar', 'Find popular community threads about this.', 17),
    ('social_search', 'similar', '看看 Reddit 上大家怎么讨论这个问题', 18),
    ('social_search', 'similar', '搜索论坛里关于这个产品的讨论', 19),
    ('social_search', 'similar', '找一下用户对这个产品的真实反馈', 20),
    ('social_search', 'similar', '看看社区里有没有人遇到过这个问题', 21),
    ('social_search', 'similar', '搜索 Reddit 上相关的用户经验', 22),
    ('social_search', 'similar', '看看论坛用户对这个问题怎么说', 23),
    ('social_search', 'similar', '找一下社交平台上的相关讨论', 24),
    ('social_search', 'similar', '搜索社区里的相关帖子', 25),
    ('social_search', 'similar', 'Search Reddit for user discussions about this.', 26),
    ('social_search', 'similar', 'Find forum discussions about this topic.', 27),
    ('social_search', 'similar', 'Look for user experiences with this product.', 28),
    ('social_search', 'similar', 'Search community discussions about this issue.', 29),
    ('social_search', 'similar', 'Find Reddit posts where people discuss this.', 30),
    ('social_search', 'similar', 'Look for firsthand experiences from users.', 31),
    ('social_search', 'similar', 'Search forums for discussions about this.', 32),
    ('social_search', 'similar', 'See what people in online communities are saying.', 33);
