-- Chat session-memory v2: compaction checkpoint.
-- sessions.compaction is the durable backup of the conversation's compression state:
--   { revision, through_message_id, through_created_at,
--     summary, summary_chars, last_compaction_at, fold_count }
-- Invariant: `summary` fully covers every model-facing message from the session head
-- through `through_message_id` INCLUSIVE; the first message after that id is the start
-- of the live tail. Summary and watermark are updated by ONE conditional UPDATE
-- (revision CAS), so a partial state (advanced watermark, stale summary) is impossible.
-- Normal chat turns never read this column: the client carries the summary in its live
-- state; the server reads the checkpoint only for recovery, compaction, and reconcile.
ALTER TABLE sessions ADD COLUMN IF NOT EXISTS compaction jsonb;
