# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: retrieval/v1/retrieval.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'retrieval/v1/retrieval.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cretrieval/v1/retrieval.proto\x12\x0cretrieval.v1\"\x9c\x01\n\x0fRetrieveRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\r\n\x05top_k\x18\x02 \x01(\x05\x12;\n\x07\x66ilters\x18\x03 \x03(\x0b\x32*.retrieval.v1.RetrieveRequest.FiltersEntry\x1a.\n\x0c\x46iltersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"9\n\x10RetrieveResponse\x12%\n\x04hits\x18\x01 \x03(\x0b\x32\x17.retrieval.v1.SearchHit\"B\n\tSearchHit\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x01\x12\x0c\n\x04meta\x18\x04 \x01(\t\"\x0f\n\rHealthRequest\" \n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xa2\x01\n\x10RetrievalService\x12I\n\x08Retrieve\x12\x1d.retrieval.v1.RetrieveRequest\x1a\x1e.retrieval.v1.RetrieveResponse\x12\x43\n\x06Health\x12\x1b.retrieval.v1.HealthRequest\x1a\x1c.retrieval.v1.HealthResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'retrieval.v1.retrieval_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RETRIEVEREQUEST_FILTERSENTRY']._loaded_options = None
  _globals['_RETRIEVEREQUEST_FILTERSENTRY']._serialized_options = b'8\001'
  _globals['_RETRIEVEREQUEST']._serialized_start=47
  _globals['_RETRIEVEREQUEST']._serialized_end=203
  _globals['_RETRIEVEREQUEST_FILTERSENTRY']._serialized_start=157
  _globals['_RETRIEVEREQUEST_FILTERSENTRY']._serialized_end=203
  _globals['_RETRIEVERESPONSE']._serialized_start=205
  _globals['_RETRIEVERESPONSE']._serialized_end=262
  _globals['_SEARCHHIT']._serialized_start=264
  _globals['_SEARCHHIT']._serialized_end=330
  _globals['_HEALTHREQUEST']._serialized_start=332
  _globals['_HEALTHREQUEST']._serialized_end=347
  _globals['_HEALTHRESPONSE']._serialized_start=349
  _globals['_HEALTHRESPONSE']._serialized_end=381
  _globals['_RETRIEVALSERVICE']._serialized_start=384
  _globals['_RETRIEVALSERVICE']._serialized_end=546
# @@protoc_insertion_point(module_scope)
