# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from retrieval.v1 import retrieval_pb2 as retrieval_dot_v1_dot_retrieval__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in retrieval/v1/retrieval_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RetrievalServiceStub:
    """RetrievalService owns the whole retrieval stack (embedding, vector/FTS recall,
    RRF fusion, cross-encoder rerank, query rewrite). The API process talks to it over
    gRPC instead of loading the RAG pipeline in-process.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Retrieve = channel.unary_unary(
                '/retrieval.v1.RetrievalService/Retrieve',
                request_serializer=retrieval_dot_v1_dot_retrieval__pb2.RetrieveRequest.SerializeToString,
                response_deserializer=retrieval_dot_v1_dot_retrieval__pb2.RetrieveResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/retrieval.v1.RetrievalService/Health',
                request_serializer=retrieval_dot_v1_dot_retrieval__pb2.HealthRequest.SerializeToString,
                response_deserializer=retrieval_dot_v1_dot_retrieval__pb2.HealthResponse.FromString,
                _registered_method=True)


class RetrievalServiceServicer:
    """RetrievalService owns the whole retrieval stack (embedding, vector/FTS recall,
    RRF fusion, cross-encoder rerank, query rewrite). The API process talks to it over
    gRPC instead of loading the RAG pipeline in-process.
    """

    def Retrieve(self, request, context):
        """Retrieve the top_k text chunks for a query.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Liveness/readiness probe.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RetrievalServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Retrieve': grpc.unary_unary_rpc_method_handler(
                    servicer.Retrieve,
                    request_deserializer=retrieval_dot_v1_dot_retrieval__pb2.RetrieveRequest.FromString,
                    response_serializer=retrieval_dot_v1_dot_retrieval__pb2.RetrieveResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=retrieval_dot_v1_dot_retrieval__pb2.HealthRequest.FromString,
                    response_serializer=retrieval_dot_v1_dot_retrieval__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'retrieval.v1.RetrievalService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('retrieval.v1.RetrievalService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RetrievalService:
    """RetrievalService owns the whole retrieval stack (embedding, vector/FTS recall,
    RRF fusion, cross-encoder rerank, query rewrite). The API process talks to it over
    gRPC instead of loading the RAG pipeline in-process.
    """

    @staticmethod
    def Retrieve(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retrieval.v1.RetrievalService/Retrieve',
            retrieval_dot_v1_dot_retrieval__pb2.RetrieveRequest.SerializeToString,
            retrieval_dot_v1_dot_retrieval__pb2.RetrieveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/retrieval.v1.RetrievalService/Health',
            retrieval_dot_v1_dot_retrieval__pb2.HealthRequest.SerializeToString,
            retrieval_dot_v1_dot_retrieval__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
