"""Generated protobuf/gRPC stubs loader.

The stubs live in ``packages/shared/proto/retrieval/v1/`` (installed as the ``retrieval.v1``
package) and are generated by ``scripts/gen_proto.sh``. This module re-exports them so
consumers just do ``from core.infrastructure.proto import retrieval_pb2``.
"""
from retrieval.v1 import retrieval_pb2, retrieval_pb2_grpc

__all__ = ["retrieval_pb2", "retrieval_pb2_grpc"]
