"""Generated protobuf/gRPC stubs loader.

The stubs live in ``packages/shared/proto/retrieval/v1/`` and are generated by
``scripts/gen_proto.sh`` into a top-level ``retrieval.v1`` package. Because that directory
is not a wheel-installed package, we put it on ``sys.path`` once here and re-export the
modules so consumers just do ``from core.infrastructure.proto import retrieval_pb2``.
"""
import sys
from pathlib import Path

_PROTO_DIR = Path(__file__).resolve().parents[2] / "shared" / "proto"
if str(_PROTO_DIR) not in sys.path:
    sys.path.insert(0, str(_PROTO_DIR))

from retrieval.v1 import retrieval_pb2, retrieval_pb2_grpc  # noqa: E402

__all__ = ["retrieval_pb2", "retrieval_pb2_grpc"]
