"""Generated protobuf/gRPC stubs loader.

The stubs live in ``packages/shared/proto/retrieval/v1/`` (installed as the ``retrieval.v1``
package) and are generated by ``scripts/gen_proto.sh``. This module re-exports them so
consumers just do ``from core.infrastructure.proto import retrieval_pb2``.

If the ``retrieval`` package is not installed (e.g. a stale editable install), the loader
falls back to the in-repo ``packages/shared/proto`` directory, so both the API (grpc
retrieval mode) and the retrieval service run from a plain checkout without re-installing.
"""
from __future__ import annotations

import sys
from pathlib import Path


def _load():
    try:
        from retrieval.v1 import retrieval_pb2, retrieval_pb2_grpc

        return retrieval_pb2, retrieval_pb2_grpc
    except ModuleNotFoundError:
        pass
    # Stale editable install: point at the in-repo generated stubs, three parents up
    # (packages/core/infrastructure/proto.py → packages/shared/proto).
    repo_proto = Path(__file__).resolve().parents[2] / "shared" / "proto"
    if str(repo_proto) not in sys.path:
        sys.path.insert(0, str(repo_proto))
    # The failed import above may have cached a partial ``retrieval`` namespace package;
    # drop it so the re-import actually searches the newly added path.
    for name in (
        "retrieval",
        "retrieval.v1",
        "retrieval.v1.retrieval_pb2",
        "retrieval.v1.retrieval_pb2_grpc",
    ):
        sys.modules.pop(name, None)
    from retrieval.v1 import retrieval_pb2, retrieval_pb2_grpc

    return retrieval_pb2, retrieval_pb2_grpc


retrieval_pb2, retrieval_pb2_grpc = _load()

__all__ = ["retrieval_pb2", "retrieval_pb2_grpc"]
